{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.14","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[],"dockerImageVersionId":30804,"isInternetEnabled":false,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"markdown","source":"Q1. Explain why we have to use the Exception class while creating a Custom Exception.\r\nIn Python, the Exception class is the base class for all built-in exceptions. When we create a custom exception class in Python, we inherit from the Exception class so that our custom exception can have all the properties and methods of the base Exception class.\r\n\r\nInheriting from the Exception class allows our custom exception to behave like a built-in exception. It enables us to use common exception handling techniques like catching and raising exceptions in the same way we would with built-in exceptions.\r\n\r\nThe Exception class provides a number of useful properties and methods that our custom exception can use. For example, we can set an error message for our custom exception using the init method of the Exception class. We can also provide a string representation of our custom exception using the str method, which can be useful for printing out error messages or debugging.\r\n\r\nIn short, using the Exception class while creating a custom exception allows us to create exceptions that are more specific to our own code or application while still having all the features and functionality of a built-in exception.","metadata":{}},{"cell_type":"markdown","source":"Q2. Write a python program to print Python Exception Hierarchy.","metadata":{}},{"cell_type":"code","source":"# import inspect module\nimport inspect\n\n# our treeClass function\ndef treeClass(cls, ind = 0):\n\t\n\t# print name of the class\n\tprint ('-' * ind, cls.__name__)\n\t\n\t# iterating through subclasses\n\tfor i in cls.__subclasses__():\n\t\ttreeClass(i, ind + 3)\n\nprint(\"Hierarchy for Built-in exceptions is : \")\n\n# inspect.getmro() Return a tuple\n# of class clsâ€™s base classes.\n\n# building a tree hierarchy\ninspect.getclasstree(inspect.getmro(BaseException))\n\n# function call\ntreeClass(BaseException)","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-09T13:10:35.287637Z","iopub.execute_input":"2024-12-09T13:10:35.291201Z","iopub.status.idle":"2024-12-09T13:10:35.359764Z","shell.execute_reply.started":"2024-12-09T13:10:35.291118Z","shell.execute_reply":"2024-12-09T13:10:35.357130Z"}},"outputs":[{"name":"stdout","text":"Hierarchy for Built-in exceptions is : \n BaseException\n--- Exception\n------ TypeError\n--------- InvalidType\n--------- MultipartConversionError\n--------- FloatOperation\n--------- DTypePromotionError\n--------- UFuncTypeError\n------------ UFuncTypeError\n--------------- UFuncTypeError\n------------ UFuncTypeError\n--------------- UFuncTypeError\n--------------- UFuncTypeError\n--------- ConversionError\n------ StopAsyncIteration\n------ StopIteration\n------ ImportError\n--------- ModuleNotFoundError\n------------ PackageNotFoundError\n--------- ZipImportError\n------ OSError\n--------- ConnectionError\n------------ BrokenPipeError\n------------ ConnectionAbortedError\n------------ ConnectionRefusedError\n------------ ConnectionResetError\n--------------- RemoteDisconnected\n--------- BlockingIOError\n--------- ChildProcessError\n--------- FileExistsError\n--------- FileNotFoundError\n------------ ExecutableNotFoundError\n--------- IsADirectoryError\n--------- NotADirectoryError\n--------- InterruptedError\n------------ InterruptedSystemCall\n--------- PermissionError\n--------- ProcessLookupError\n--------- TimeoutError\n--------- UnsupportedOperation\n--------- itimer_error\n--------- OSError\n--------- herror\n--------- gaierror\n--------- SSLError\n------------ SSLCertVerificationError\n------------ SSLZeroReturnError\n------------ SSLWantWriteError\n------------ SSLWantReadError\n------------ SSLSyscallError\n------------ SSLEOFError\n--------- Error\n------------ SameFileError\n--------- SpecialFileError\n--------- ExecError\n--------- ReadError\n--------- URLError\n------------ HTTPError\n------------ ContentTooShortError\n--------- BadGzipFile\n--------- UnidentifiedImageError\n------ EOFError\n--------- IncompleteReadError\n------ RuntimeError\n--------- RecursionError\n--------- NotImplementedError\n------------ ZMQVersionError\n------------ StdinNotImplementedError\n--------- _DeadlockError\n--------- BrokenBarrierError\n--------- BrokenExecutor\n------------ BrokenThreadPool\n--------- SendfileNotAvailableError\n--------- VariableError\n--------- TooHardError\n------ NameError\n--------- UnboundLocalError\n------ AttributeError\n--------- FrozenInstanceError\n------ SyntaxError\n--------- IndentationError\n------------ TabError\n--------- ParseError\n------ LookupError\n--------- IndexError\n------------ AxisError\n------------ OutOfBounds\n--------- KeyError\n------------ NoSuchKernel\n------------ UnknownBackend\n--------- CodecRegistryError\n------ ValueError\n--------- UnicodeError\n------------ UnicodeEncodeError\n------------ UnicodeDecodeError\n------------ UnicodeTranslateError\n--------- UnsupportedOperation\n--------- JSONDecodeError\n--------- MalformedError\n--------- InvalidResource\n--------- InvalidOperation\n--------- InvalidValue\n--------- MessageDefect\n------------ NoBoundaryInMultipartDefect\n------------ StartBoundaryNotFoundDefect\n------------ CloseBoundaryNotFoundDefect\n------------ FirstHeaderLineIsContinuationDefect\n------------ MisplacedEnvelopeHeaderDefect\n------------ MissingHeaderBodySeparatorDefect\n------------ MultipartInvariantViolationDefect\n------------ InvalidMultipartContentTransferEncodingDefect\n------------ UndecodableBytesDefect\n------------ InvalidBase64PaddingDefect\n------------ InvalidBase64CharactersDefect\n------------ InvalidBase64LengthDefect\n------------ HeaderDefect\n--------------- InvalidHeaderDefect\n--------------- HeaderMissingRequiredValue\n--------------- NonPrintableDefect\n--------------- ObsoleteHeaderDefect\n--------------- NonASCIILocalPartDefect\n--------------- InvalidDateDefect\n--------- Error\n--------- IllegalMonthError\n--------- IllegalWeekdayError\n--------- SSLCertVerificationError\n--------- UnsupportedDigestmodError\n--------- ParserError\n--------- ClassNotFound\n--------- ClipboardEmpty\n--------- MacroToEdit\n--------- InvalidVersion\n--------- AxisError\n--------- LinAlgError\n--------- DefusedXmlException\n------------ DTDForbidden\n------------ EntitiesForbidden\n------------ ExternalReferenceForbidden\n------------ NotSupportedError\n--------- NonIntersectingPathException\n------ AssertionError\n------ ArithmeticError\n--------- FloatingPointError\n--------- OverflowError\n--------- ZeroDivisionError\n------------ DivisionByZero\n------------ DivisionUndefined\n--------- DecimalException\n------------ Clamped\n------------ Rounded\n--------------- Underflow\n--------------- Overflow\n------------ Inexact\n--------------- Underflow\n--------------- Overflow\n------------ Subnormal\n--------------- Underflow\n------------ DivisionByZero\n------------ FloatOperation\n------------ InvalidOperation\n--------------- ConversionSyntax\n--------------- DivisionImpossible\n--------------- DivisionUndefined\n--------------- InvalidContext\n------ SystemError\n--------- CodecRegistryError\n------ ReferenceError\n------ MemoryError\n--------- MemoryError\n------ BufferError\n------ Warning\n--------- UserWarning\n------------ GetPassWarning\n------------ FormatterWarning\n------------ VisibleDeprecationWarning\n------------ RankWarning\n------------ ConversionWarning\n------------ RankWarning\n--------- EncodingWarning\n--------- DeprecationWarning\n------------ Python37DeprecationWarning\n------------ ProvisionalWarning\n------------ ModuleDeprecationWarning\n------------ MatplotlibDeprecationWarning\n--------- PendingDeprecationWarning\n--------- SyntaxWarning\n--------- RuntimeWarning\n------------ ProactorSelectorThreadWarning\n------------ UnknownTimezoneWarning\n------------ ComplexWarning\n------------ DecompressionBombWarning\n--------- FutureWarning\n------------ ProvisionalCompleterWarning\n------------ MaskedArrayFutureWarning\n--------- ImportWarning\n--------- UnicodeWarning\n--------- BytesWarning\n--------- ResourceWarning\n--------- DeprecatedTzFormatWarning\n--------- MathTextWarning\n------ _OptionError\n------ error\n------ Verbose\n------ Error\n------ TokenError\n------ StopTokenizing\n------ GoogleAuthError\n--------- TransportError\n--------- RefreshError\n------------ ReauthFailError\n--------------- ReauthSamlChallengeFailError\n--------- UserAccessTokenError\n--------- DefaultCredentialsError\n------------ MalformedError\n------------ InvalidResource\n------------ InvalidOperation\n------------ InvalidValue\n------------ InvalidType\n------------ OSError\n--------- MutualTLSChannelError\n--------- ClientCertError\n--------- OAuthError\n------ MessageError\n--------- MessageParseError\n------------ HeaderParseError\n------------ BoundaryError\n--------- MultipartConversionError\n--------- CharsetError\n------ Incomplete\n------ error\n------ _GiveupOnSendfile\n------ Error\n------ HTTPException\n--------- NotConnected\n--------- InvalidURL\n--------- UnknownProtocol\n--------- UnknownTransferEncoding\n--------- UnimplementedFileMode\n--------- IncompleteRead\n--------- ImproperConnectionState\n------------ CannotSendRequest\n------------ CannotSendHeader\n------------ ResponseNotReady\n--------- BadStatusLine\n------------ RemoteDisconnected\n--------- LineTooLong\n------ ClassFoundException\n------ EndOfBlock\n------ _Error\n------ SubprocessError\n--------- CalledProcessError\n--------- TimeoutExpired\n------ TraitError\n------ Error\n------ Error\n--------- CancelledError\n--------- TimeoutError\n--------- InvalidStateError\n------ TimeoutError\n------ InvalidStateError\n------ LimitOverrunError\n------ QueueEmpty\n------ QueueFull\n------ Empty\n------ Full\n------ ZMQBaseError\n--------- ZMQError\n------------ ContextTerminated\n------------ Again\n------------ InterruptedSystemCall\n--------- ZMQBindError\n--------- NotDone\n------ PickleError\n--------- PicklingError\n--------- UnpicklingError\n------ _Stop\n------ error\n------ ArgumentError\n------ error\n------ ReturnValueIgnoredError\n------ ArgumentError\n------ ArgumentTypeError\n------ ConfigError\n--------- ConfigLoaderError\n------------ ArgumentError\n--------- ConfigFileNotFound\n------ ConfigurableError\n--------- MultipleInstanceError\n------ ApplicationError\n------ InvalidPortNumber\n------ error\n------ LZMAError\n------ RegistryError\n------ _GiveupOnFastCopy\n------ Error\n--------- NoSectionError\n--------- DuplicateSectionError\n--------- DuplicateOptionError\n--------- NoOptionError\n--------- InterpolationError\n------------ InterpolationMissingOptionError\n------------ InterpolationSyntaxError\n------------ InterpolationDepthError\n--------- ParsingError\n------------ MissingSectionHeaderError\n------ NoIPAddresses\n------ BadZipFile\n------ LargeZipFile\n------ BadEntryPoint\n------ NoSuchEntryPoint\n------ DuplicateKernelError\n------ ErrorDuringImport\n------ NotOneValueFound\n------ CannotEval\n------ Error\n------ OptionError\n------ BdbQuit\n------ Restart\n------ FindCmdError\n------ HomeDirError\n------ ProfileDirError\n------ IPythonCoreError\n--------- TryNext\n--------- UsageError\n--------- StdinNotImplementedError\n------ InputRejected\n------ GetoptError\n------ ErrorToken\n------ PrefilterError\n------ AliasError\n--------- InvalidAliasError\n------ Error\n--------- InterfaceError\n--------- DatabaseError\n------------ InternalError\n------------ OperationalError\n------------ ProgrammingError\n------------ IntegrityError\n------------ DataError\n------------ NotSupportedError\n------ Warning\n------ ExceptionGroup\n------ SpaceInInput\n------ DOMException\n--------- IndexSizeErr\n--------- DomstringSizeErr\n--------- HierarchyRequestErr\n--------- WrongDocumentErr\n--------- InvalidCharacterErr\n--------- NoDataAllowedErr\n--------- NoModificationAllowedErr\n--------- NotFoundErr\n--------- NotSupportedErr\n--------- InuseAttributeErr\n--------- InvalidStateErr\n--------- SyntaxErr\n--------- InvalidModificationErr\n--------- NamespaceErr\n--------- InvalidAccessErr\n--------- ValidationErr\n------ ValidationError\n------ EditReadOnlyBuffer\n------ _Retry\n------ InvalidLayoutError\n------ HeightIsUnknownError\n------ ExpatError\n------ ParseEscape\n------ GuardRejection\n------ ParserSyntaxError\n------ InternalParseError\n------ _PositionUpdatingFinished\n------ SimpleGetItemNotFound\n------ UncaughtAttributeError\n------ HasNoContext\n------ ParamIssue\n------ _JediError\n--------- InternalError\n--------- WrongVersion\n--------- RefactoringError\n------ OnErrorLeaf\n------ InvalidPythonEnvironment\n------ InteractivelyDefined\n------ KillEmbedded\n------ Error\n--------- NoSuchProcess\n------------ ZombieProcess\n--------- AccessDenied\n--------- TimeoutExpired\n------ _Ipv6UnsupportedError\n------ KeyReuseError\n------ UnknownKeyError\n------ LeakedCallbackError\n------ BadYieldError\n------ ReturnValueIgnoredError\n------ Return\n------ QueueEmpty\n------ QueueFull\n------ DebuggerInitializationError\n------ Error\n--------- ProtocolError\n--------- ResponseError\n--------- Fault\n------ _Error\n------ UnableToResolveVariableException\n------ InvalidTypeInArgsException\n------ ConverterError\n--------- ConverterLockError\n------ MAError\n--------- MaskError\n------ DecompressionBombError\n------ ParseBaseException\n--------- ParseException\n--------- ParseFatalException\n------------ ParseSyntaxException\n------ RecursiveGrammarException\n------ _ParseActionIndexError\n------ BadRequiredStrength\n------ DuplicateConstraint\n------ DuplicateEditVariable\n------ UnknownConstraint\n------ UnknownEditVariable\n------ UnsatisfiableConstraint\n------ NonGuiException\n------ InvalidIndexError\n------ TerminateTrajectory\n--- GeneratorExit\n--- SystemExit\n--- KeyboardInterrupt\n--- CancelledError\n--- BaseExceptionGroup\n------ ExceptionGroup\n","output_type":"stream"}],"execution_count":1},{"cell_type":"markdown","source":"","metadata":{}},{"cell_type":"code","source":"Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\nThe ArithmeticError class is a built-in exception class in Python that serves as the base class for all exceptions that occur during arithmetic operations. Some of the errors defined in the ArithmeticError class include FloatingPointError, ZeroDivisionError, and OverflowError. Here are two examples of ArithmeticError exceptions:\n\nZeroDivisionError: This exception is raised when attempting to divide by zero.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"a = 10\nb = 0\n\ntry:\n    result = a / b\nexcept ZeroDivisionError:\n    print(\"Error: division by zero\")","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-09T13:11:09.260060Z","iopub.execute_input":"2024-12-09T13:11:09.261088Z","iopub.status.idle":"2024-12-09T13:11:09.266316Z","shell.execute_reply.started":"2024-12-09T13:11:09.261048Z","shell.execute_reply":"2024-12-09T13:11:09.265268Z"}},"outputs":[{"name":"stdout","text":"Error: division by zero\n","output_type":"stream"}],"execution_count":2},{"cell_type":"code","source":"OverflowError: This exception is raised when the result of an arithmetic operation is too large to be represented.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"import sys\n\na = sys.maxsize\nb = 2\n\ntry:\n    result = a * b\nexcept OverflowError:\n    print(\"Error: result too large to represent\")","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-09T13:11:29.444051Z","iopub.execute_input":"2024-12-09T13:11:29.444412Z","iopub.status.idle":"2024-12-09T13:11:29.449670Z","shell.execute_reply.started":"2024-12-09T13:11:29.444378Z","shell.execute_reply":"2024-12-09T13:11:29.448548Z"}},"outputs":[],"execution_count":4},{"cell_type":"code","source":"Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\nThe LookupError class is a built-in exception class in Python that serves as the base class for all exceptions that occur when a key or index is not found in a container. It is a subclass of the Exception class and is used to catch all types of lookup errors in a generic way.\n\nTwo examples of lookup errors that are defined as subclasses of LookupError are KeyError and IndexError.\n\nKeyError is raised when a dictionary key is not found in a dictionary, while IndexError is raised when an index is out of range for a list or tuple.\n\nHere are examples of both KeyError and IndexError:","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"code","source":"# KeyError example\nd = {'a': 1, 'b': 2, 'c': 3}\ntry:\n    print(d['d'])\nexcept KeyError:\n    print(\"Error: key not found\")\n\n# IndexError example\nlst = [1, 2, 3]\ntry:\n    print(lst[3])\nexcept IndexError:\n    print(\"Error: index out of range\")","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-09T13:11:49.962827Z","iopub.execute_input":"2024-12-09T13:11:49.963196Z","iopub.status.idle":"2024-12-09T13:11:49.969268Z","shell.execute_reply.started":"2024-12-09T13:11:49.963164Z","shell.execute_reply":"2024-12-09T13:11:49.968142Z"}},"outputs":[{"name":"stdout","text":"Error: key not found\nError: index out of range\n","output_type":"stream"}],"execution_count":5},{"cell_type":"markdown","source":"Q5. Explain ImportError. What is ModuleNotFoundError?\r\nImportError is a built-in exception class in Python that is raised when a module or package cannot be imported. This can happen for various reasons, such as a missing or invalid module name, a missing or inaccessible module file, or an error in the module's initialization code.\r\n\r\nModuleNotFoundError is a subclass of ImportError that was introduced in Python 3.6 to provide a more specific error message when a module cannot be found. Prior to Python 3.6, ImportError was raised for all module import failures, regardless of whether the module was missing or there was another type of import error.\r\n\r\nHere is an example of ModuleNotFoundError:","metadata":{}},{"cell_type":"code","source":"try:\n    import my_module\nexcept ModuleNotFoundError:\n    print(\"Error: module not found\")","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2024-12-09T13:12:08.892365Z","iopub.execute_input":"2024-12-09T13:12:08.892763Z","iopub.status.idle":"2024-12-09T13:12:08.898975Z","shell.execute_reply.started":"2024-12-09T13:12:08.892726Z","shell.execute_reply":"2024-12-09T13:12:08.897782Z"}},"outputs":[{"name":"stdout","text":"Error: module not found\n","output_type":"stream"}],"execution_count":6},{"cell_type":"code","source":"Q6. List down some best practices for exception handling in python.\nHere are some best practices for exception handling in Python:\n\nBe specific: Catch only the exceptions that you expect to occur, and be as specific as possible in the exception type. This makes it easier to debug and maintain the code.\n\nKeep it simple: Keep the try block as small as possible and avoid nesting try-except blocks whenever possible. This makes the code more readable and easier to maintain.\n\nProvide useful error messages: Provide useful and informative error messages in the except block that describe what went wrong and how to fix it.\n\nUse logging: Use logging to track errors and debug information. This can help you identify and diagnose problems in your code.\n\nDon't use exceptions for flow control: Avoid using exceptions for flow control. Exceptions should only be used to handle exceptional cases, not to control the normal flow of the program.\n\nClean up resources: Use the finally block to clean up any resources (e.g., files, sockets, database connections) that were opened in the try block, regardless of whether an exception was raised or not.\n\nHandle exceptions at the right level: Handle exceptions at the appropriate level of your program. For example, if an exception occurs in a lower-level function, it might be better to handle the exception at a higher level that can take appropriate action.","metadata":{"trusted":true},"outputs":[],"execution_count":null},{"cell_type":"markdown","source":"","metadata":{}}]}